language: c

os:
  - linux
  - osx

compiler:
 - gcc
 - clang

script:
 - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CC" = "gcc" ]; then export CC=gcc-4.8; fi
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./configure --disable-openssl --enable-assert; else ./configure --enable-assert; fi
 - make
 - sudo make install

notifications:
 email:
  - staticfox@staticfox.net
